### ISSUE TITLE
Calendar app white page on Firefox version 63.0.1 (nc20)

### ISSUE THREAD

**Issue by florom** [nextcloud/calendar#2757]
Hi Devs,

nextcloud 20.0.4
php 7.3
mariadb latest
calendarApp version 2.1.2
Browser Firefox 63.0.1

Calendar App shows only white page when clicked.

I have upgraded now to nc20 and I unfortunatly saw that calendar now shows a white page in Firefox 63.0.1. (It works on Firefox 84) but due to company restrictions I have to work with 63.0.1.

It would be nice if this could be fixed.

Thank you.

EDIT:
#### Browser log
```
GEThttps://mydomain.com/index.php/apps/calendar/
[HTTP/1.1 200 OK 147ms]
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Strict-Transport-Security: The site specified a header that did not include a 'max-age' directive.[Learn More] calendar
GEThttps://mydomain.com/core/js/dist/main.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/core/js/dist/files_fileinfo.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/core/js/dist/files_client.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/js/core/merged-template-prepend.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/core/dd86-2079-server.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
GEThttps://mydomain.com/core/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/accessibility/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/accessibility/js/accessibilityoca.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/apporder/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/apporder/js/apporder.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/core/dd86-2079-css-variables.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
GEThttps://mydomain.com/apps/encryption/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/encryption/js/encryption.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/files_sharing/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/files_sharing/js/dist/main.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/epubreader/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/epubreader/js/plugin.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/files_pdfviewer/js/files_pdfviewer-public.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/files_videoplayer/js/main.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/notifications/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/notifications/js/notifications-main.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/firstrunwizard/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/firstrunwizard/js/about.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/theming/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/theming/js/theming.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/user_status/js/user-status-menu.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/calendar/l10n/en_GB.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/calendar/js/calendar.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/core/js/dist/unified-search.js?v=acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/apps/apporder/css/apporder.css?v=cfab4291-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/notifications/0577-2079-styles.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/deck/bf70-2079-deck.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/notes/23fb-2079-global.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/spreed/8869-2079-unified-search.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/user_status/3acc-2079-user-status-menu.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/calendar/9562-2079-calendar.css?v=35d886836a77b200ed99db01068506d3-acc84847-9
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/css/icons/icons-vars.css?v=1608632352
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/apps/theming/styles?v=9
[HTTP/1.1 200 OK 0ms]
Unknown property 'scrollbar-color'.  Declaration dropped. dd86-2079-server.css:1:409
Unknown property 'scrollbar-width'.  Declaration dropped. dd86-2079-server.css:1:462
Unknown pseudo-class or pseudo-element '-webkit-scrollbar'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:2023
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-track-piece'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:2064
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:2125
Error in parsing value for 'position'.  Declaration dropped. dd86-2079-server.css:1:2352
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:2563
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:4185
Unrecognised at-rule or error parsing at-rule '@-ms-viewport'. dd86-2079-server.css:1:23285
Unknown property 'appearance'.  Declaration dropped. dd86-2079-server.css:1:32555
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:36115
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:47963
Error in parsing value for 'max-width'.  Declaration dropped. dd86-2079-server.css:1:50083
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:52100
Unknown pseudo-class or pseudo-element '-webkit-progress-value'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:53569
Unknown pseudo-class or pseudo-element '-webkit-progress-bar'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:53632
Unknown pseudo-class or pseudo-element '-webkit-progress-value'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:53814
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:54288
Unknown pseudo-class or pseudo-element '-webkit-search-cancel-button'.  Ruleset ignored due to bad selector. dd86-2079-server.css:1:66832
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:84583
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:86511
Error in parsing value for 'position'.  Declaration dropped. dd86-2079-server.css:1:96950
Error in parsing value for 'position'.  Declaration dropped. dd86-2079-server.css:1:121660
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:128250
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:128909
Unknown property 'line-break'.  Declaration dropped. dd86-2079-server.css:1:132180
Unknown property 'user-select'.  Declaration dropped. dd86-2079-server.css:1:136652
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. apporder.css:18:10
Error in parsing value for 'word-wrap'.  Declaration dropped. 0577-2079-styles.css:1:2592
Unknown property 'user-select'.  Declaration dropped. 9562-2079-calendar.css:1:9476
Error in parsing value for 'max-width'.  Declaration dropped. 9562-2079-calendar.css:1:33578
No OC found index.js:46:4
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:541
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
Notifications permissions denied App.vue:302
GEThttps://mydomain.com/index.php/avatar/flonext/32?v=0
[HTTP/1.1 200 OK 0ms]
GEThttps://mydomain.com/index.php/svg/core/logo/logo?color=fff&v=1
[HTTP/1.1 200 OK 0ms]
XHRGEThttps://mydomain.com/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/1.1 200 OK 196ms]
XHRPUThttps://mydomain.com/index.php/apps/user_status/heartbeat
[HTTP/1.1 204 No Content 260ms]
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:48:9
Unknown property 'user-select'.  Declaration dropped. calendar:178:14
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:667:10
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:1044:9
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:1051:9
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:1055:9
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:1307:10
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:175:9
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:182:9
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:186:9
Expected 'none', URL, or filter function but found 'Alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:438:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:132:11
Unknown property '-moz-border-radius'.  Declaration dropped. calendar:136:22
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:146:11
Unknown property '-moz-border-radius'.  Declaration dropped. calendar:150:22
Unknown property 'zoom'.  Declaration dropped. calendar:9:10
Expected declaration but found '*'.  Skipped to next declaration. calendar:10:5
Unknown property 'user-select'.  Declaration dropped. calendar:49:27
Error in parsing value for 'background-image'.  Declaration dropped. calendar:53:23
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. calendar:55:13
Error in parsing value for 'background-image'.  Declaration dropped. calendar:69:23
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. calendar:71:13
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:137:13
Error in parsing value for 'background-image'.  Declaration dropped. calendar:202:23
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. calendar:204:13
Error in parsing value for 'background'.  Declaration dropped. calendar:261:887
Error in parsing value for 'background'.  Declaration dropped. calendar:271:888
Error in parsing value for 'background'.  Declaration dropped. calendar:283:2529
Error in parsing value for 'background-image'.  Declaration dropped. calendar:307:23
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. calendar:309:13
Error in parsing value for 'background-image'.  Declaration dropped. calendar:319:23
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. calendar:321:13
Unknown property 'user-select'.  Declaration dropped. calendar:395:27
Unknown property 'user-select'.  Declaration dropped. calendar:582:27
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. calendar:585:13
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. calendar:15:10
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Error in parsing value for 'left'.  Declaration dropped. calendar:1:490
Error in parsing value for 'left'.  Declaration dropped. calendar:1:811
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1117
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1434
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Error in parsing value for 'word-break'.  Declaration dropped. calendar:1:71
Unknown property 'backdrop-filter'.  Declaration dropped. calendar:1:689
XHRGEThttps://mydomain.com/ocs/v2.php/search/providers?from=%2Fapps%2Fcalendar%2F
[HTTP/1.1 200 OK 335ms]
Error in parsing value for 'position'.  Declaration dropped. calendar:1:167
Unknown property 'user-select'.  Declaration dropped. calendar:1:385
Unknown pseudo-class or pseudo-element '-ms-clear'.  Ruleset ignored due to bad selector. calendar:1:34858
Unknown property 'user-select'.  Declaration dropped. calendar:1:35648
Unknown property 'user-select'.  Declaration dropped. calendar:1:38971
Error in parsing value for 'left'.  Declaration dropped. calendar:1:490
Error in parsing value for 'left'.  Declaration dropped. calendar:1:811
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1117
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1434
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Error in parsing value for 'max-width'.  Declaration dropped. calendar:1:1924
Unknown property 'user-select'.  Declaration dropped. calendar:1:4129
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Error in parsing value for 'left'.  Declaration dropped. calendar:1:490
Error in parsing value for 'left'.  Declaration dropped. calendar:1:811
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1117
XHRGEThttps://mydomain.com/index.php/apps/apporder/getOrder
[HTTP/1.1 200 OK 229ms]
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1434
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Unknown pseudo-class or pseudo-element '-ms-clear'.  Ruleset ignored due to bad selector. calendar:1:34858
Unknown property 'user-select'.  Declaration dropped. calendar:1:35648
Unknown property 'user-select'.  Declaration dropped. calendar:1:38971
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Error in parsing value for 'left'.  Declaration dropped. calendar:1:490
Error in parsing value for 'left'.  Declaration dropped. calendar:1:811
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1117
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1434
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Error in parsing value for 'left'.  Declaration dropped. calendar:1:490
Error in parsing value for 'left'.  Declaration dropped. calendar:1:811
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1117
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1434
Unknown property 'user-select'.  Declaration dropped. calendar:13:23
Unknown property 'user-select'.  Declaration dropped. calendar:86:23
Unknown property 'speak'.  Declaration dropped. calendar:90:9
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. calendar:99:27
Error in parsing value for 'outline'.  Declaration dropped. calendar:151:22
Unknown property 'user-select'.  Declaration dropped. calendar:176:25
Error in parsing value for 'position'.  Declaration dropped. calendar:397:15
Error in parsing value for 'position'.  Declaration dropped. calendar:414:13
Error in parsing value for 'position'.  Declaration dropped. calendar:41:17
ReferenceError: ResizeObserver is not defined[Learn More] autosize.js:25:6
Unknown property 'line-break'.  Declaration dropped. calendar:1:208
Error in parsing value for 'left'.  Declaration dropped. calendar:1:490
Error in parsing value for 'left'.  Declaration dropped. calendar:1:811
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1117
Error in parsing value for 'top'.  Declaration dropped. calendar:1:1434
Unknown property 'rx'.  Declaration dropped. calendar:1:295
Unknown property 'ry'.  Declaration dropped. calendar:1:319
Unknown property 'x'.  Declaration dropped. calendar:1:501
Unknown property 'y'.  Declaration dropped. calendar:1:570
Unknown property 'y'.  Declaration dropped. calendar:1:638
Unknown pseudo-class or pseudo-element '-webkit-search-decoration'.  Ruleset ignored due to bad selector. calendar:1:986
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
session heartbeat polling started session-heartbeat.js:97:1
Files_PDFViewer initialized for public page 
Object { isPublicPage: null, canDownload: true, isSecureViewerAvailable: false }
public.js:30:1
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
Strict-Transport-Security: The site specified a header that did not include a 'max-age' directive.[Learn More] notifications
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
Strict-Transport-Security: The site specified a header that did not include a 'max-age' directive.[Learn More] heartbeat
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
Strict-Transport-Security: The site specified a header that did not include a 'max-age' directive.[Learn More] getOrder
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }
ConsoleLogger.js:42:10
Strict-Transport-Security: The site specified a header that did not include a 'max-age' directive.[Learn More] providers
XHRGEThttps://mydomain.com/index.php/apps/encryption/ajax/getStatus
[HTTP/1.1 200 OK 145ms]
XHRGEThttps://mydomain.com/ocs/v2.php/apps/user_status/api/v1/user_status
[HTTP/1.1 200 OK 214ms]
GEThttps://mydomain.com/apps/calendar/img/favicon-touch.png
GEThttps://mydomain.com/apps/calendar/img/favicon.ico
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2
Strict-Transport-Security: The site specified a header that did not include a 'max-age' directive.[Learn More] getStatus
Strict-Transport-Security: The site specified a header that did not include a 'max-age' directive.[Learn More] user_status
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:2 
```

**Comment by tcitworld** [comment]
Please fill the __entire__ [issue template](https://raw.githubusercontent.com/nextcloud/calendar/master/.github/ISSUE_TEMPLATE/bug.md).

Important information, like browser console logs, are missing that would help us resolve this issue.

**Comment by fweng322** [comment]
Maybe the same one with #2734 ?

**Comment by muzzah** [comment]
I am also seeing this. Not just Calendar, but also with tasks andd contacts

**Comment by syntron** [comment]
I'm seeing this using calendar 2.1.3

working: Chromium (87.0.4280.88)
not working: falkon (3.1.0 / QtWebEngine 5.12.7) <= my default browser

using nextcloud 20.0.4.0; tasks and contacts seems to be fine

it was working before the latest update (2.1.2 => 2.1.3)

falkon console log:

index.js:46 No OC found
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
notifications-main.js?v=649afad2-3:303 Notifications permissions denied
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
calendar.js?v=649afad2-3:2 [INFO] calendar: 
Initial settings:
	- AppVersion: 2.1.3
	- EventLimit: true
	- FirstRun: false
	- ShowWeekNumbers: true
	- ShowTasks: true
	- ShowWeekends: true
	- SkipPopover: false
	- SlotDuration: 00:30:00
	- TalkEnabled: true
	- TasksEnabled: true
	- Timezone: automatic
 
{app: "calendar", uid: "matthias"}
calendar.js?v=649afad2-3:2 [DEBUG] calendar: The calendar app is using version 2.2019c of the timezone database 
{app: "calendar", uid: "matthias"}
DevTools failed to parse SourceMap: https://[...nextcloud...]/apps/notifications/js/notifications-main.js.map?v=7e353c6…
calendar.js?v=649afad2-3:2 TypeError: e.replaceAll is not a function
    at Mp (calendar.js?v=649afad2-3:2)
    at i.options (calendar.js?v=649afad2-3:2)
    at vn.get (calendar.js?v=649afad2-3:2)
    at vn.evaluate (calendar.js?v=649afad2-3:2)
    at i.options (calendar.js?v=649afad2-3:2)
    at i.ls (calendar.js?v=649afad2-3:2)
    at i.e._render (calendar.js?v=649afad2-3:2)
    at i.r (calendar.js?v=649afad2-3:2)
    at vn.get (calendar.js?v=649afad2-3:2)
    at new vn (calendar.js?v=649afad2-3:2)
calendar.js?v=649afad2-3:2 TypeError: Cannot read property '$el' of undefined
    at i.mounted (calendar.js?v=649afad2-3:2)
    at He (calendar.js?v=649afad2-3:2)
    at sn (calendar.js?v=649afad2-3:2)
    at Object.insert (calendar.js?v=649afad2-3:2)
    at x (calendar.js?v=649afad2-3:2)
    at Dn.__patch__ (calendar.js?v=649afad2-3:2)
    at Dn.e._update (calendar.js?v=649afad2-3:2)
    at Dn.r (calendar.js?v=649afad2-3:2)
    at vn.get (calendar.js?v=649afad2-3:2)
    at new vn (calendar.js?v=649afad2-3:2)
session-heartbeat.js:97 session heartbeat polling started
public.js:30 Files_PDFViewer initialized for public page 
{isPublicPage: null, canDownload: true, isSecureViewerAvailable: false}
[Violation] Forced reflow while executing JavaScript took 126ms
23
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
[... repeated...]
calendar.js?v=649afad2-3:2 [INFO] calendar: Updated moment locale: de 
{app: "calendar", uid: "matthias"}
ConsoleLogger.js:42 [DEBUG] unified-search: Unified Search initialized with the following providers 
{0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, 10: {…}, 11: {…}, 12: {…}, 13: {…}, 14: {…}, 15: {…}, 16: {…}, app: "unified-search", uid: "matthias"}
calendar.js?v=649afad2-3:2 [DEBUG] calendar: Current user principal is /remote.php/dav/principals/users/matthias/ 
{app: "calendar", uid: "matthias"}
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
[... repeated...]

**Comment by florom** [comment]
Hi Devs,

After the Update from 20.0.4 to 20.0.5 I also see the headloine and the left side but the calendar grid is ok.
Since I do not have the options to reopen this incidident I am afraid it will never get fixed.

Thanks for first attempt to fix.

**Comment by PatriceVigier** [comment]
Calendard 2.1.3
Nextcloud 20.0.5.2
White page on Firefox 69.0.3
The console error is
TypeError: "e.replaceAll is not a function"
and
TypeError: "this.$refs.fullCalendar is undefined"

Work on Chrome 87

**Comment by florom** [comment]
Hi Devs,
Thanks for fixing it.
Finally with 2.2.0 Calendar version it works.

Thanks again
