### ISSUE TITLE
Categories of an event can't be updated

### ISSUE THREAD

**Issue by st3iny** [nextcloud/calendar#5785]
### Steps to reproduce

1. Edit and event.
2. Open the sidebar editor.
3. Add some categories.
4. Save the event.

### Expected behavior

It should save the event and all selected categories.

### Actual behaviour

An error toast is shown, the event is not saved and the category picker is emptied.

https://github.com/nextcloud/calendar/assets/1479486/cb9cba57-fb4b-4eea-a5d6-22ba113860d2

### Calendar app version

main

### Browser log

```Text
Uncaught (in promise) TypeError: aValue.replace is not a function
    at Object.toICAL (ical.js:430:1)
    at ICAL.stringify.stringify.value (ical.js:1698:1)
    at ICAL.stringify.stringify.multiValue (ical.js:1675:1)
    at ICAL.stringify.stringify.property (ical.js:1612:1)
    at ICAL.stringify.stringify.component (ical.js:1498:1)
    at ICAL.stringify.stringify.component (ical.js:1507:1)
    at Component.toString (ical.js:2772:1)
    at CalendarComponent.toICS (index.es.mjs:9161:1)
    at Store.updateCalendarObject (calendarObjects.js:226:1)
    at Array.wrappedActionHandler (vuex.esm.js:851:1)
```

**Comment by Gehilfe** [comment]
Same Problem here.

**Comment by comsyspro** [comment]
same here. can you downgrade somehow to calendar v4.6.7 and if yes how to do it?

**Comment by phantom943** [comment]
@comsyspro yes you can
https://help.nextcloud.com/t/how-to-downgrade-calendar-app-from-3-0-3-to-3-0-2/129915/2
here are the instructions.
However, the "invite circle to event" feature was added in 4.7.0, so downgrading wouldn't be feasible for us.

**Comment by comsyspro** [comment]
i downgraded to v4.7.0 but v4.6.7 was not possible because this version is not compatible. so the only solution is to fix the code.

**Comment by b90g** [comment]
Calendar 4.7.2 on NC 28.0.5 with php8.2.18 - having this issue.

**Comment by protegh** [comment]
Adding a category from the pull down list works with version 4.7.3 but adding a new own category is still broken.

**Comment by comsyspro** [comment]
i just updated to the new calendar version 4.7.3 and i can't even create a normal entry so it seems that something failed with the new code.

please have a look:
![image](https://github.com/nextcloud/calendar/assets/13809377/f8783a0f-ec47-49ba-8f77-ee529e3e8294)

![image](https://github.com/nextcloud/calendar/assets/13809377/859528fe-21ce-4cae-9dad-83ac77589161)

**Comment by st3iny** [comment]
@comsyspro It looks like your only calendar (`Aufgaben`) does not support VEVENTs because it was created through the Tasks app. Please create a new calendar and try again.

In general, please open a new issue next time and try not to revive old issues with unrelated bugs as you are generating a lot of notifications this way.

**Comment by comsyspro** [comment]
the error appeared after the upgrade with the events categories, so i suspected this was the problem. creating a new calendar did not resolve the issue and even deleting the new calendar failed. removing and reinstalling the calendar didn't help either. only a new installation of nextcloud was successful. there may be some fragments in the database that caused the problem.

**Comment by nmsw** [comment]
I have the exact same issue. The calendar was not created in the tasks app. A new regular calendar shows the same issue. Re-installing Nextcloud is not an option.

**Comment by miaulalala** [comment]
@nmsw Please open a new issue.
